#!/usr/bin/env python3
"""Refresh the auto-generated free-model list in README.md.

Fetches OpenRouter's model catalog (no auth required), keeps the free and
chat-capable ones, and rewrites the block between the FREE_MODELS markers.
Reuses the same predicates the router uses, so the README matches runtime.

Usage:
    python scripts/update_models.py
"""

from __future__ import annotations

import pathlib
import re
import sys

import httpx

from freerouter.config import settings
from freerouter.models import is_chat_capable, is_free

START = "<!-- FREE_MODELS:START -->"
END = "<!-- FREE_MODELS:END -->"
README = pathlib.Path(__file__).resolve().parent.parent / "README.md"


def fetch_free() -> list[dict]:
    resp = httpx.get(f"{settings.openrouter_base_url}/models", timeout=30)
    resp.raise_for_status()
    data = resp.json().get("data", [])
    free = [m for m in data if is_free(m) and is_chat_capable(m)]
    # Same priority as the registry: `:free`-suffixed first, then larger context.
    free.sort(
        key=lambda m: (m["id"].endswith(":free"), int(m.get("context_length") or 0)),
        reverse=True,
    )
    return free


def render(free: list[dict]) -> str:
    lines = [
        START,
        f"_{len(free)} free, chat-capable models (prompt + completion priced at $0). "
        "Auto-generated by `scripts/update_models.py`._",
        "",
        "| Model ID | Context |",
        "|----------|---------|",
    ]
    for m in free:
        ctx = int(m.get("context_length") or 0)
        lines.append(f"| `{m['id']}` | {ctx:,} |" if ctx else f"| `{m['id']}` | — |")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    free = fetch_free()
    block = render(free)

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        print(f"markers not found in README.md ({START} ... {END})", file=sys.stderr)
        return 1

    new = pattern.sub(lambda _: block, text)
    if new == text:
        print(f"no change ({len(free)} free models)")
        return 0

    README.write_text(new, encoding="utf-8")
    print(f"updated: {len(free)} free models")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
